packer {
  required_plugins {
    azure = {
      source  = "github.com/hashicorp/azure"
      version = "~> 2"
    }
  }
}

source "azure-arm" "autogenerated_1" {
  azure_tags = {
    dept = "Engineering"
    task = "Image deployment"
  }
  client_id                         = "493f3ff4-90dc-49fb-9577-1490818ba371"
  client_secret                     = "KER8Q~hd1-BkjxXts2zlLWWRUqF9UB6dzP11TceF"
  image_offer                       = "0001-com-ubuntu-server-jammy"
  image_publisher                   = "canonical"
  image_sku                         = "22_04-lts"
  build_resource_group_name         = "b3-gr5"
  managed_image_name                = "tonypacker"
  managed_image_resource_group_name = "b3-gr5"
  os_type                           = "Linux"
  subscription_id                   = "c56aea2c-50de-4adc-9673-6a8008892c21"
  tenant_id                         = "16763265-1998-4c96-826e-c04162b1e041"
  vm_size                           = "Standard_B1s"
}

build {
  sources = ["source.azure-arm.autogenerated_1"]

  provisioner "shell" {
    execute_command = "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}'"
    inline          = ["apt-get update", "apt-get upgrade -y", "apt-get -y install nginx"]
    inline_shebang  = "/bin/sh -x"
  }

  provisioner "file" {
    source      = "./index.html"
    destination = "./index.html"
  }

  provisioner "shell" {
    inline = ["sudo rm /var/www/html/index.nginx-debian.html", "sudo mv ./index.html /var/www/html/index.nginx-debian.html"]
  }

}